### ISSUE TITLE
Count of lines may be different

### ISSUE THREAD

**Issue by EvilFreelancer** [arily/RouterOSResponseArray#1]
https://github.com/arily/RouterOSResponseArray/blob/83828ac71ba35c24851477dab994d8d2a4e34622/ROSRA.php#L21

You used `array_chunk` standart method of PHP language, but you should know what RouterOS may return assymetric array, which will have different count of lines for each item started from `!re`.

Look at [my solution](https://github.com/EvilFreelancer/routeros-api-php/blob/master/src/Client.php#L209) and you will get how to solve the issue.

**Comment by arily** [comment]
since this is out-dated now I will link to your repo and warning anyone accidentally accessed to not use this.
